/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Shopping_cart;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

import java.util.Scanner;


public class App {

    public String url = "jdbc:mysql://localhost:3306/i42022_ravit";
    public String user = "root";
    public String password = "";


    //TEST CONNECT
    public void connect_Sql(){
        try {     
            Connection con = DriverManager.getConnection(url, user, password);
            System.out.println("Connect success");
            Statement st = con.createStatement();

        } catch (SQLException ex) {
           //errr
           System.out.printf("%s",ex);
        }
    }
    
    //List all product 
    public void list_product(){
        String query_select = "SELECT * FROM products;";
    
        try {     
            Connection con = DriverManager.getConnection(url, user, password);
                   System.out.println("Connect success");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query_select);
                   // iterate through the java resultset
                   System.out.printf("==================================================\n");
                while (rs.next())
                {
                    int id = rs.getInt("id");
                    String name = rs.getString("name");
                    Float price = rs.getFloat("price");
                    // print the results
                    System.out.format("ID: %s | Name: %s | Price: %s.\n", id, name, price);
                }

        } catch (SQLException ex) {
            //errr
            System.out.printf("%s",ex);
        }
    }
    //add products
    public void add_product(){

        Scanner input = new Scanner(System.in);

        System.out.print("Enter Product name: ");
        String name = input.nextLine();
        System.out.print("Enter Product Price: ");
        Float price = input.nextFloat();

        String query_insert = String.format("INSERT INTO products set name = \"%s\", price =\"%.2f\";", name,price);
                               
        try {     
            Connection con = DriverManager.getConnection(url, user, password);
                    // System.out.println("Connect success");
            Statement st = con.createStatement();
                    st.execute(query_insert);
                    System.out.println("Insert Success");
        } catch (SQLException ex) {
            //errr
            System.out.printf("%s",ex);
        }
    }
    //update product by id
    public void update_product(){

        Scanner input = new Scanner(System.in);

        System.out.print("Enter Product ID you want to update : ");
        int ID = input.nextInt();
        input.nextLine(); 
        

        System.out.print("Enter new Product name: ");
        String name = input.nextLine();
        System.out.print("Enter new Product Price: ");
        Float price = input.nextFloat();

        String query_update = String.format("UPDATE products SET name = \"%s\", price =%f WHERE id=%d;", name,price,ID);
    
        try {     
            Connection con = DriverManager.getConnection(url, user, password);
                    // System.out.println("Connect success");
            Statement st = con.createStatement();
                    st.execute(query_update);
                    System.out.println("Update Success");
        } catch (SQLException ex) {
            //errr
            // System.out.printf("%s",ex);
            System.out.print("Cannot Update Because ID is not exists. Please list data to see all ID that exists.");
        }
    }
    
    public void delete_product(){
        Scanner input = new Scanner(System.in);

        System.out.print("Enter Product ID or Name you want to delete : ");
        String delete_key = input.nextLine(); 
        
   

        String query_delete = String.format("DELETE FROM products WHERE name=\""+delete_key+"\" or id=\""+delete_key+"\";");
       
        try {     
            Connection con = DriverManager.getConnection(url, user, password);
                    // System.out.println("Connect success");
            Statement st = con.createStatement();
                    st.execute(query_delete);
                    System.out.println("Delete Success");
        } catch (SQLException ex) {
            //errr
            // System.out.printf("%s",ex);
            System.out.print("Cannot Delete Because ID or name is not exists. Please list data to see all ID that exists.");
        }
    }

    public void search_product(){
        Scanner input = new Scanner(System.in);

        System.out.print("Enter Product Name: ");
        String search_key = input.nextLine(); 
        
   

        String query_select = "SELECT * FROM products where name=\""+search_key+"\";";
    
        try {     
            Connection con = DriverManager.getConnection(url, user, password);
                   System.out.println("Connect success");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query_select);
                   // iterate through the java resultset
                   System.out.printf("==================================================\n");
                while (rs.next())
                {
                    int id = rs.getInt("id");
                    String name = rs.getString("name");
                    Float price = rs.getFloat("price");
                    // print the results
                    System.out.format("ID: %s | Name: %s | Price: %s.\n", id, name, price);
                }

        } catch (SQLException ex) {
            //errr
            System.out.printf("%s",ex);
        }
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void pressAnyKeyToContinue() { 
        System.out.println("\nPress Enter key to continue...");
        try{
            System.in.read();
        }  
        catch(Exception e){}  
    }

    public int select_menu(){
        Scanner in = new Scanner(System.in);
        System.out.println("Menu"+
        " \n\t1. List All Products "+
        " \n\t2. Add new Product "+
        " \n\t3. Update Exitsting Product by id "+
        " \n\t4. Delete product by name or id "+
        " \n\t5. Search product by name "+
        " \n\t0. Exit ");
        System.out.print("Enter choice [1-5]: ");
        int choice = in.nextInt();
        return choice;
    }
 

    public static void main(String[] args) {
        
        //import part
        App test = new App();
        Scanner sc = new Scanner(System.in);
    
         do{
            
            int choice = test.select_menu();


            if(choice == 0 || choice > 5) break;

            switch(choice){
                case 1: 
                    test.list_product();
                    pressAnyKeyToContinue();
                    break;
                case 2:
                   test.add_product();
                    pressAnyKeyToContinue();
                    break;
                case 3:
                      test.update_product();
                    pressAnyKeyToContinue();
                    break;
                case 4:
                     test.delete_product();
                    pressAnyKeyToContinue();
                    break;
                case 5:
                     test.search_product();
                    pressAnyKeyToContinue();
                    break;
                  
                default:
                    break;
            }

        }   while(true);
       
    }
}
